In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.warn("warning message")

/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/4030482396.py:5: UserWarning: warning message
  warnings.warn("warning message")

In [2]:
dataset=pd.read_csv("preprocess_cancer.csv")

In [3]:
dataset

,Unnamed: 0,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,1
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,1
2,2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,0
3,3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1,0
4,4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,535,57,1,1,1,1,1,1,1,1,1,1,2,1,1,0,0
536,536,55,1,1,1,1,1,2,1,1,1,1,2,1,1,1,0
537,537,55,2,1,1,1,1,1,1,1,1,1,2,1,1,0,0
538,538,69,1,1,1,1,1,2,1,1,1,1,2,1,1,0,0
539,539,59,1,1,1,1,1,1,1,1,1,1,1,1,2,1,0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             540 non-null    int64
 1   AGE                    540 non-null    int64
 2   SMOKING                540 non-null    int64
 3   YELLOW_FINGERS         540 non-null    int64
 4   ANXIETY                540 non-null    int64
 5   PEER_PRESSURE          540 non-null    int64
 6   CHRONIC DISEASE        540 non-null    int64
 7   FATIGUE                540 non-null    int64
 8   ALLERGY                540 non-null    int64
 9   WHEEZING               540 non-null    int64
 10  ALCOHOL CONSUMING      540 non-null    int64
 11  COUGHING               540 non-null    int64
 12  SHORTNESS OF BREATH    540 non-null    int64
 13  SWALLOWING DIFFICULTY  540 non-null    int64
 14  CHEST PAIN             540 non-null    int64
 15  GENDER_M               540 non-null    int64
 16  LUNG_CANCER_YES        540 non-null    int64
dtypes: int64(17)
memory usage: 71.8 KB

In [5]:
dataset.shape

(540, 17)

In [6]:
dataset1=dataset.drop("Unnamed: 0",axis=1)

In [7]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE                    540 non-null    int64
 1   SMOKING                540 non-null    int64
 2   YELLOW_FINGERS         540 non-null    int64
 3   ANXIETY                540 non-null    int64
 4   PEER_PRESSURE          540 non-null    int64
 5   CHRONIC DISEASE        540 non-null    int64
 6   FATIGUE                540 non-null    int64
 7   ALLERGY                540 non-null    int64
 8   WHEEZING               540 non-null    int64
 9   ALCOHOL CONSUMING      540 non-null    int64
 10  COUGHING               540 non-null    int64
 11  SHORTNESS OF BREATH    540 non-null    int64
 12  SWALLOWING DIFFICULTY  540 non-null    int64
 13  CHEST PAIN             540 non-null    int64
 14  GENDER_M               540 non-null    int64
 15  LUNG_CANCER_YES        540 non-null    int64
dtypes: int64(16)
memory usage: 67.6 KB

# selection k algoritham

In [9]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
def select_kbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    select_kfeatures=fit1.transform(indep_x)
    Scolumns=test.get_feature_names_out()
    print(Scolumns)
    #selected_colum=indep_x.columns[test.get_support()]
    #print(selected_colum)
    return select_kfeatures

In [10]:
indep_x=dataset1.drop("LUNG_CANCER_YES",axis=1)
dep_y=dataset1["LUNG_CANCER_YES"]

In [11]:
indep_x.columns

Index(['AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY', 'PEER_PRESSURE',
       'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'GENDER_M'],
      dtype='object')

In [12]:
dep_y

0      1
1      1
2      0
3      0
4      0
      ..
535    0
536    0
537    0
538    0
539    0
Name: LUNG_CANCER_YES, Length: 540, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    scx=StandardScaler()
    x_train=scx.fit_transform(x_train)
    x_test=scx.transform(x_test)
    return x_train,x_test,y_train,y_test

In [14]:
def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)

    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)

    from sklearn.metrics import accuracy_score
    accuracy=accuracy_score(y_test,y_pred)

    from sklearn.metrics import classification_report
    cl_report=classification_report(y_test,y_pred)

    return classifier,accuracy,cl_report,x_test,y_test,cm

In [15]:
from sklearn.linear_model import LogisticRegression
def logistic(x_train,y_train,x_test):
    classifier=LogisticRegression()
    classifier.fit(x_train,y_train)
    classifier,accuracy,cl_report,x_train,y_train,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,cl_report,x_train,y_train,cm

In [16]:
from sklearn.svm import LinearSVC
def svm_linear(x_train,y_train,x_test):
    classifier=LinearSVC()
    from sklearn.svm import SVC
    classifier.fit(x_train, y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,Accuracy,report,x_test,y_test,cm

In [17]:
from sklearn.svm import SVC
def svm_NL(x_train,y_train,x_test):
    classifier=SVC()
    classifier.fit(x_train, y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,Accuracy,report,x_test,y_test,cm

In [18]:
from sklearn.neighbors import KNeighborsClassifier
def knn(x_train,y_train,x_test):
    classifier=KNeighborsClassifier()
    classifier.fit(x_train, y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,Accuracy,report,x_test,y_test,cm

In [19]:
from sklearn.tree import DecisionTreeClassifier
def Decision(x_train,y_train,x_test):
    classifier=DecisionTreeClassifier()
    classifier.fit(x_train, y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,Accuracy,report,x_test,y_test,cm

In [20]:
from sklearn.ensemble import RandomForestClassifier
def random(x_train,y_train,x_test):
    classifier=RandomForestClassifier()
    classifier.fit(x_train, y_train)
    classifier,Accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,Accuracy,report,x_test,y_test,cm

In [36]:
def selectk_classification(acc_log_r,acc_svm_l,acc_svm_nl,acc_knn,acc_dec,acc_rf):
    dataframe=pd.DataFrame(index=["chisquare"],columns=["Logistic","svml","svmnl","knn","Decision","random"])
    for number,idex in enumerate(dataframe.index):
        dataframe["Logistic"][idex]=acc_log_r[number]
        dataframe["svml"][idex]=acc_svm_l[number]
        dataframe["svmnl"][idex]=acc_svm_nl[number]
        dataframe["knn"][idex]=acc_knn[number]
        dataframe["Decision"][idex]=acc_dec[number]
        dataframe["random"][idex]=acc_rf[number]
        return dataframe

In [42]:
acc_log_r=[]
acc_svm_l=[]
acc_svm_nl=[]
acc_knn=[]
acc_dec=[]
acc_rf=[]

In [41]:
kbest=select_kbest(indep_x,dep_y,7)
kbest

['ALLERGY ' 'WHEEZING' 'ALCOHOL CONSUMING' 'COUGHING'
 'SWALLOWING DIFFICULTY' 'CHEST PAIN' 'GENDER_M']

/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

array([[1, 2, 2, ..., 2, 2, 1],
       [2, 1, 1, ..., 2, 2, 1],
       [1, 2, 1, ..., 1, 2, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 2, 1]], shape=(540, 7))

In [43]:
x_train,x_test,y_train,y_test=split_scaler(kbest,dep_y)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

classifier,Accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
acc_log_r.append(Accuracy)

classifier,Accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)
acc_svm_l.append(Accuracy)

classifier,Accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)
acc_svm_nl.append(Accuracy)

classifier,Accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)
acc_knn.append(Accuracy)

classifier,Accuracy,report,x_test,y_test,cm=Decision(x_train,y_train,x_test)
acc_dec.append(Accuracy)

classifier,Accuracy,report,x_test,y_test,cm=random(x_train,y_train,x_test)
acc_rf.append(Accuracy)


result=selectk_classification(acc_log_r,acc_svm_l,acc_svm_nl,acc_knn,acc_dec,acc_rf)

(405, 7) (135, 7) (405,) (135,)

/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["Logistic"][idex]=acc_log_r[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["svml"][idex]=acc_svm_l[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["svmnl"][idex]=acc_svm_nl[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["knn"][idex]=acc_knn[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["Decision"][idex]=acc_dec[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/1505157284.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe["random"][idex]=acc_rf[number]

In [40]:
result# 2 columns

           Logistic      svml     svmnl      knn  Decision    random
chisquare  0.859259  0.859259  0.859259  0.77037  0.859259  0.859259

In [32]:
result#5 columns

           Logistic      svml     svmnl       knn  Decision    random
chisquare  0.903704  0.903704  0.888889  0.881481  0.874074  0.874074

In [44]:
result #7columns

           Logistic      svml     svmnl       knn  Decision    random
chisquare  0.933333  0.933333  0.896296  0.896296  0.896296  0.896296

# RFE(recursive feature elimination)

In [50]:
from sklearn.feature_selection import RFE
# finde best algorithem with sutable columns

def rfeFeature (indep_x,dep_y,n): # select the best column with reject same evaluation valu
    rfelist=[]
    log_model=LogisticRegression()#solver="lbfgs"
    SVC_L=LinearSVC()#random_state=0, tol=1e-5
    SVC_NL=SVC()
    KNN= KNeighborsClassifier()#n_neighbors=3
    RF=RandomForestClassifier()
    DT=DecisionTreeClassifier()#criterion="gini",max_features="aqrt",splitter="best",random_state=0
    RFEmodel_list=[log_model,SVC_L,SVC_NL,KNN,RF,DT]
    for i in RFEmodel_list:
        print(i)
        log_rfe=RFE(estimator=i,n_features_to_select=n)
        log_fit=log_rfe.fit(indep_x,dep_y)
        log_rfe_feature=log_fit.transform(indep_x)
        rfelist.append(log_rfe_feature)
        return rfelist
    selected_colum=indep_x.columns[log_fit.get_support()]
    print(selected_colum)

In [80]:
rfelist=rfeFeature(indep_x,dep_y,6)

LogisticRegression()

/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept

In [81]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accdes=[]
accrf=[]

In [82]:
def rfe_classification(acclog,accsvml,accsvmnl,accknn,accdes,accrf): 
    
    rfedataframe=pd.DataFrame(index=['Logistic','SVM_L','SVC_NL','KNN','Decision_Tree','Random'],columns=['Logistic','SVMl','SVMnl','KNN','Decision','Random',])
    for number,idex in enumerate(rfedataframe.index):
        
        rfedataframe['Logistic'][idex]=acclog[number]       
        rfedataframe['SVMl'][idex]=accsvml[number]
        rfedataframe['SVMnl'][idex]=accsvmnl[number]
        rfedataframe['KNN'][idex]=accknn[number]
        rfedataframe['Decision'][idex]=accdes[number]
        rfedataframe['Random'][idex]=accrf[number]
    return rfedataframe

In [83]:
for i in rfelist:   
    x_train, x_test, y_train, y_test=split_scaler(i,dep_y)   
    
        
    classifier,Accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
    acclog.append(Accuracy)
    
    classifier,Accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)  
    accsvml.append(Accuracy)
    
    classifier,Accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)  
    accsvmnl.append(Accuracy)
    
    classifier,Accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)  
    accknn.append(Accuracy)
    
    classifier,Accuracy,report,x_test,y_test,cm=Decision(x_train,y_train,x_test)  
    accdes.append(Accuracy)
    
    classifier,Accuracy,report,x_test,y_test,cm=random(x_train,y_train,x_test)  
    accrf.append(Accuracy)
    
result=rfe_classification(acclog,accsvml,accsvmnl,accknn,accdes,accrf)

/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/opt/anaconda3/envs/aiml/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Logistic'][idex]=acclog[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['SVMl'][idex]=accsvml[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['SVMnl'][idex]=accsvmnl[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['KNN'][idex]=accknn[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Decision'][idex]=accdes[number]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_23556/2934333543.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rfedataframe['Random'][idex]=accrf[number]

IndexError: list index out of range

In [74]:
result #2

          Logistic      SVMl     SVMnl      KNN  Decision    Random
Logistic  0.859259  0.859259  0.859259  0.77037  0.859259  0.859259
Random    0.859259  0.859259  0.859259  0.77037  0.859259  0.859259

In [67]:
result # 5

          Logistic      SVMl     SVMnl       KNN  Decision    Random
Logistic  0.940741  0.940741  0.925926  0.925926  0.918519  0.933333
SVC_NL    0.940741  0.940741  0.925926  0.925926  0.918519  0.925926
KNN       0.940741  0.940741  0.925926  0.925926  0.918519  0.933333
Random    0.940741  0.940741  0.925926  0.925926  0.918519  0.925926

In [79]:
result #6

          Logistic      SVMl     SVMnl      KNN  Decision    Random
Logistic  0.859259  0.859259  0.859259  0.77037  0.859259  0.859259
Random    0.859259  0.859259  0.859259  0.77037  0.859259  0.859259